query Shop {
    shop {
        name
        primaryDomain {
            url
            host
        }
    }
}

query ProductById($id: ID!) {
    node(id: $id) {
        id
        ... on Product {
            title
            descriptionHtml
            variants(first: 250) {
                edges {
                    node {
                        price
                        title
                        availableForSale
                        id
                    }
                }
            }
        }
    }
}

query Products {
    products(first: 99) {
        edges {
            node {
                id
                title
            }
        }
    }
}

query ProductByHandle($handle: String!) {
    productByHandle(handle: $handle) {
        id
        title
        handle
        productType
        tags
        description
        descriptionHtml
        availableForSale
        images(first: 5) {
            edges {
                node {
                    src
                    altText
                }
            }
        }
        collections(first: 1) {
            edges {
                node {
                    handle
                    title
                }
            }
        }
        metafields(first: 5) {
            edges {
                node {
                    description
                    key
                    value
                    namespace
                    id
                }
            }
        }
        priceRange {
            maxVariantPrice {
                amount
            }
            minVariantPrice {
                amount
            }
        }

        variants(first: 10) {
            edges {
                node {
                    # metafields
                    id
                    compareAtPrice
                    availableForSale
                    price
                    title
                    image {
                        altText
                        src
                    }
                }
            }
        }
    }
}

query Collections {
    collections(first: 3) {
        edges {
            node {
                title
                id
                handle
            }
        }
    }
}

query CollectionByHandle($handle: String!) {
    collectionByHandle(handle: $handle) {
        id
        title
        handle
        image {
            src
            altText
            id
        }
        products(first: 25) {
            edges {
                node {
                    title
                    id
                    handle
                    availableForSale
                    description(truncateAt: 30)
                    priceRange {
                        maxVariantPrice {
                            amount
                        }
                        minVariantPrice {
                            amount
                        }
                    }
                    images(first: 5) {
                        edges {
                            node {
                                src
                                altText
                            }
                        }
                    }
                }
            }
        }
    }
}

query CheckoutById($id: ID!) {
    node(id: $id) {
        ... on Checkout {
            id
            webUrl
            completedAt
            lineItems(first: 50) {
                edges {
                    node {
                        id
                        title
                        quantity
                        variant {
                            id
                            title
                            priceV2 {
                                amount
                            }
                            image {
                                src
                                altText
                            }
                            product {
                                title
                                handle
                            }
                        }
                    }
                }
            }
        }
    }
}
